import { Shader } from '../types';

export const INITIAL_SHADERS: Shader[] = [
  { id: 's-galaxy', name: 'Neural Galaxy', color: '#ffdc5e', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float t = u_time * u_speed * 0.5; vec3 col = vec3(0.0); for(float i=0.0; i<3.0; i++) { uv = abs(uv) * 1.4 - 1.0; float a = t + u_audio_val * 0.5; uv *= mat2(cos(a), -sin(a), sin(a), cos(a)); col += 0.005 / abs(length(uv) - 0.5) * (u_color + vec3(0.1, 0.4, 0.8)); } gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-grid', name: 'Cyber Grid', color: '#3b82f6', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float t = u_time * u_speed; float grid = abs(sin(uv.x * 10.0 + u_audio_val)) * abs(cos(uv.y * 10.0 + t)); vec3 col = u_color * smoothstep(0.4, 0.5, grid); gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-liquid', name: 'Liquid Neon', color: '#ec4899', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float t = u_time * u_speed; float n = sin(uv.x * 5.0 + t) + sin(uv.y * 5.0 + t + u_audio_val); vec3 col = mix(u_color, vec3(0.0, 1.0, 1.0), n); gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-tunnel', name: 'Infinite Tunnel', color: '#f59e0b', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float r = length(uv); float a = atan(uv.y, uv.x); float t = u_time * u_speed; float s = sin(10.0/r + t + u_audio_val * 5.0); vec3 col = u_color * smoothstep(0.1, 0.2, s); gl_FragColor = vec4(col * u_intensity / r, 1.0); }` },
  { id: 's-lava', name: 'Molten Core', color: '#ef4444', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float t = u_time * u_speed; vec3 col = vec3(0.0); float d = sin(uv.x * 10.0 + t) * cos(uv.y * 10.0 - t) + u_audio_val; col = mix(vec3(0.2, 0.0, 0.0), vec3(1.0, 0.3, 0.0), d); gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-nebula', name: 'Deep Nebula', color: '#8b5cf6', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float t = u_time * u_speed * 0.1; float n = sin(uv.x * 4.0 + t) * sin(uv.y * 4.0 - t) + u_audio_val * 0.5; vec3 col = mix(vec3(0.1, 0.0, 0.2), u_color, n); gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-matrix', name: 'Logic Rain', color: '#22c55e', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float drop = step(0.95, fract(uv.x * 50.0 + sin(floor(uv.x*50.0)))) * fract(uv.y + u_time * u_speed + u_audio_val); gl_FragColor = vec4(u_color * drop * u_intensity, 1.0); }` },
  { id: 's-void', name: 'The Void', color: '#ffffff', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float d = length(uv); float s = sin(10.0 * d - u_time * u_speed) + u_audio_val; gl_FragColor = vec4(u_color * smoothstep(0.4, 0.5, s) * u_intensity, 1.0); }` },
  { id: 's-web', name: 'Neural Web', color: '#06b6d4', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float a = atan(uv.y, uv.x); float r = length(uv); float line = abs(sin(a * 10.0 + u_time)) * abs(sin(r * 20.0 - u_time)) + u_audio_val; gl_FragColor = vec4(u_color * step(0.8, line) * u_intensity, 1.0); }` },
  { id: 's-plasma', name: 'Bio Plasma', color: '#ef4444', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float t = u_time * u_speed; float d = distance(uv, vec2(0.5)) + u_audio_val * 0.2; float n = sin(uv.x * 10.0 + t) * cos(uv.y * 10.0 - t); vec3 col = u_color * (1.0 - d) + n; gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-prism', name: 'Prism Rings', color: '#10b981', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float r = length(uv); float t = u_time * u_speed; float ring = abs(sin(r * 20.0 - t * 5.0 + u_audio_val * 10.0)); vec3 col = u_color / (ring * 50.0); gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-flare', name: 'Solar Flare', color: '#f97316', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float r = length(uv); float beam = abs(sin(atan(uv.y, uv.x) * 10.0 + u_time * u_speed)); vec3 col = u_color * beam * (1.0-r) * (1.0 + u_audio_val * 2.0); gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-hyperspace', name: 'Hyperspace', color: '#3b82f6', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float a = atan(uv.y, uv.x); float r = length(uv); float star = pow(abs(sin(a * 50.0 + u_time * 10.0)), 20.0) / r + u_audio_val; gl_FragColor = vec4(u_color * star * u_intensity, 1.0); }` },
  { id: 's-waves', name: 'Acid Waves', color: '#ec4899', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float w = sin(uv.x * 20.0 + u_time * u_speed) * cos(uv.y * 20.0 + u_time) + u_audio_val; gl_FragColor = vec4(u_color * w * u_intensity, 1.0); }` },
  { id: 's-kaleido', name: 'Kaleido Pulse', color: '#ffdc5e', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float a = mod(atan(uv.y, uv.x), 3.1415/3.0); float r = length(uv); vec2 p = vec2(cos(a), sin(a)) * r; float d = sin(p.x * 10.0 + u_time) + u_audio_val; gl_FragColor = vec4(u_color * d * u_intensity, 1.0); }` },
  { id: 's-neonweb', name: 'Neon Web', color: '#10b981', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float line = abs(sin(uv.x * 30.0 + u_time)) * abs(cos(uv.y * 30.0 - u_time)) + u_audio_val; gl_FragColor = vec4(u_color * step(0.7, line) * u_intensity, 1.0); }` },
  { id: 's-pixel', name: 'Pixel Glitch', color: '#f43f5e', code: `void main() { vec2 uv = floor(gl_FragCoord.xy / 20.0) * 20.0 / u_resolution.xy; float n = fract(sin(dot(uv, vec2(12.9898, 78.233))) * 43758.5453) + u_audio_val; gl_FragColor = vec4(u_color * n * u_intensity, 1.0); }` },
  { id: 's-bloom', name: 'Fractal Bloom', color: '#fb7185', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float r = length(uv); float a = atan(uv.y, uv.x); float f = abs(cos(a*3.0 + u_time*u_speed)) * 0.5 + 0.5; vec3 col = u_color * smoothstep(f, f+0.02, r + u_audio_val*0.2); gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-starfield', name: 'Star Field', color: '#ffffff', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float star = pow(abs(sin(uv.x*100.0)*cos(uv.y*100.0)), 20.0); vec3 col = u_color * star * (1.0 + u_audio_val * 20.0); gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-geo', name: 'Geo Storm', color: '#06b6d4', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float d = max(abs(uv.x), abs(uv.y)); float shape = step(0.3 + u_audio_val * 0.2, d) * step(d, 0.4 + u_audio_val * 0.2); vec3 col = u_color * shape; gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-flow', name: 'Chromatic Flow', color: '#8b5cf6', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float t = u_time * u_speed; vec3 col = 0.5 + 0.5 * cos(t + uv.xyx + vec3(0,2,4)); col *= sin(uv.x * 10.0 + t) * u_audio_val; gl_FragColor = vec4(col * u_intensity, 1.0); }` },
  { id: 's-rings', name: 'Sonic Rings', color: '#3b82f6', code: `void main() { vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution.xy) / u_resolution.y; float r = length(uv); float ring = abs(sin(r * 50.0 - u_time * 10.0)) + u_audio_val; gl_FragColor = vec4(u_color * smoothstep(0.4, 0.5, ring) * u_intensity, 1.0); }` },
  { id: 's-sparks', name: 'Electric Sparks', color: '#ffdc5e', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float spark = step(0.99, fract(uv.x * 10.0 + u_time)) * step(0.99, fract(uv.y * 10.0 - u_time)) + u_audio_val; gl_FragColor = vec4(u_color * spark * u_intensity, 1.0); }` },
  { id: 's-bio', name: 'Bio Pulse', color: '#22c55e', code: `void main() { vec2 uv = gl_FragCoord.xy / u_resolution.xy; float d = distance(uv, vec2(0.5)); float s = sin(d * 40.0 - u_time * 5.0) * 0.5 + 0.5 + u_audio_val; gl_FragColor = vec4(u_color * s * (1.0-d) * u_intensity, 1.0); }` }
];

